In [4]:
import numpy 

In [5]:
chi = numpy.zeros((3,4))

In [43]:
def P_l(l, chi):
    M,N = numpy.shape(chi)
    mat_min = numpy.zeros((M,N))
    for i in range(M):
        for j in range(N):
            element = (chi+l*numpy.ones((M,N)))[i,j]
            print(element)
            mat_min[i,j] =  min(element, 1)
    mat_max = numpy.zeros((M,N))
    for i in range(M):
        for j in range(N):
            mat_max[i,j] =  max(0, mat_min[i,j])
    return mat_max

In [45]:
A = numpy.array([0.1,0.2,0.2,0.7]).reshape(2,2)
print(A)
P_l(0.4,A)

[[0.1 0.2]
 [0.2 0.7]]
0.5
0.6000000000000001
0.6000000000000001
1.1


array([[0.5, 0.6],
       [0.6, 1. ]])

In [13]:
numpy.min(A +1, 1)

array([2, 3])